core/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();


Route::group(['middleware' => 'auth'], function (){
	Route::get('/', 'Frontend\HomeController@index')->name('home');
	Route::get('/customer/cart', 'Frontend\HomeController@index');
	Route::get('/search/query={name}', 'Frontend\HomeController@index');
	Route::get('/{id}', 'Frontend\HomeController@index');
	/**
	 * BACKEND
	 */
	Route::group([ 'prefix' => 'private'], function(){
		Route::get('home', 'HomeController@index')->name('dashboard');
		Route::post('itemsBy', 'ReturnItemController@apiItems')->name('api.itemsBy');
		Route::get('getSku/{id}', 'ItemController@getSku')->name('getSku');
		Route::get('returnItem/approve/{id}', 'ReturnItemController@approve')->name('returnItems.approve');
		Route::get('getAlamat/{cus_id}/{type}', 'SalesOrderController@getAlamat')->name('getAlamat');
		Route::get('downloadCSVex', function(){
			return response()->download(Storage::disk('local')->getDriver()->getAdapter()->getPathPrefix().'/public/[CONTOH MARAVILLOSA].csv');
		})->name('downloadCSVex')->middleware('permission:item');
		Route::resource('warehouseTransfers', 'WarehouseTransferController')->middleware('permission:warehouse-transfer');
		Route::resource('items', 'ItemController')->middleware('permission:item');
		Route::resource('items-variant', 'ItemVariantController')->middleware('permission:item');
		Route::resource('activityLogs', 'ActivityLogController')->middleware('permission:activity-logs');
		Route::resource('returnItems', 'ReturnItemController')->middleware('permission:return-item');
		
		Route::group(['prefix' => 'sales', 'middleware' => 'permission:sales'], function (){
			Route::get('print-invoice/{id}', 'SalesOrderController@printInvoice')->name('print-invoice')->middleware('permission:sales-order');
			Route::get('sales/approve/{id}/{jenis}', 'SalesOrderController@approve')->name('salesOrders.approve')->middleware('permission:sales-order');
			Route::resource('salesOrders', 'SalesOrderController')->middleware('permission:sales-order');
			Route::resource('invoices', 'InvoicesController')->middleware('permission:invoice');
			Route::get('purchase/{id}', 'PurchaseOrderController@approve')->name('purchaseOrders.approve')->middleware('permission:purchase-order');
			Route::resource('purchaseOrders', 'PurchaseOrderController')->middleware('permission:purchase-order');
			Route::resource('shipments', 'ShipmentController')->middleware('permission:shipment');
			Route::get('shipments/create/{id}', 'ShipmentController@create')->name('shipments.buat')->middleware('permission:shipment');
			Route::get('shipments/approve/{id}', 'ShipmentController@approve')->name('shipments.approve')->middleware('permission:shipment');
		});
		
		Route::group(['prefix' => 'report', 'namespace' => 'Report', 'middleware' => 'permission:reports'], function (){
			Route::get('purchase', 'PurchaseController@index')->name('report.purchase')->middleware('permission:report-purchase');
			Route::get('purchase/detail/{date}', 'PurchaseController@detail')->name('report.purchase.detail')->middleware('permission:report-purchase');
			Route::get('sales', 'SalesController@index')->name('report.sales')->middleware('permission:report-sales');
			Route::get('sales/detail/{date}', 'SalesController@detail')->name('report.sales.detail')->middleware('permission:report-sales');
			Route::get('warehouses', 'WarehousesController@index')->name('report.warehouses')->middleware('permission:report-stock');
			/**	FILTER */
			Route::post('purchase/filter', 'PurchaseController@filter')->name('filter.purchase')->middleware('permission:report-purchase');
			Route::post('sales/filter', 'SalesController@filter')->name('filter.sales')->middleware('permission:report-sales');
			Route::post('warehouses/filter', 'WarehousesController@filter')->name('filter.item')->middleware('permission:report-stock');
			Route::get('item/find', 'WarehousesController@apiNamaBarang')->name('api.findNamaBarang')->middleware('permission:report-stock');
			Route::post('item/find/variant', 'WarehousesController@apiNamaVariant')->name('api.findNamaVariant')->middleware('permission:report-stock');
		});
		
		Route::group(['prefix' => 'setting', 'middleware'=> ['permission:settings']], function (){
			Route::resource('users', 'UsersController')->middleware('permission:users');
			Route::resource('warehouses', 'WarehouseController')->middleware('permission:warehouses');
			Route::resource('brands', 'BrandController')->middleware('permission:brands');
			Route::resource('categories', 'CategoryController')->middleware('permission:categories');
			Route::resource('salesType', 'SalesTypeController')->middleware('permission:sales-type');
			Route::resource('suplliers', 'SupllierController')->middleware('permission:suppliers');
			Route::resource('customers', 'CustomerController')->middleware('permission:customers');
			Route::resource('paymentMethods', 'PaymentMethodController')->middleware('permission:payment-methods');
			Route::resource('taxes', 'TaxController')->middleware('permission:taxes');
			Route::resource('permissions', 'PermissionController')->middleware('permission:permissions');
			Route::resource('roles', 'RolesController')->middleware('permission:roles');
			Route::resource('departments', 'DepartmentController');
			Route::resource('satuans', 'SatuanController');
			Route::resource('itemVariants', 'ItemVariantController');
		});
		
		Route::group(['prefix' => 'datatables'], function(){
			Route::get('user', 'DatatablesController@getUsers')->name('datatables.users');
			Route::get('warehouses', 'DatatablesController@getWarehouses')->name('datatables.warehouses');
			Route::get('brands', 'DatatablesController@getBrands')->name('datatables.brands');
			Route::get('categories', 'DatatablesController@getCategories')->name('datatables.categories');
			Route::get('sales', 'DatatablesController@getSales')->name('datatables.sales');
			Route::get('suplliers', 'DatatablesController@getSuplliers')->name('datatables.suplliers');
			Route::get('customers', 'DatatablesController@getCustomers')->name('datatables.customers');
			Route::get('items', 'DatatablesController@getItems')->name('datatables.items');
			Route::get('itemsSales', 'DatatablesController@getItemsSales')->name('datatables.itemsSales');
			Route::get('itemsPurchase', 'DatatablesController@getItemsPurchase')->name('datatables.itemsPurchase');
			Route::get('salesOrders', 'DatatablesController@getSalesOrders')->name('datatables.salesOrders');
			Route::get('paymentMethods', 'DatatablesController@getPaymentMethods')->name('datatables.paymentMethods');
			Route::get('warehouseTransfer', 'DatatablesController@getWarehouseTransfer')->name('datatables.warehouseTransfer');
			Route::get('itemsWT', 'DatatablesController@getItemsWT')->name('datatables.itemsWT');
			Route::get('logs', 'DatatablesController@getActivityLog')->name('datatables.logs');
			Route::get('purchaseOrder', 'DatatablesController@getPurchaseOrders')->name('datatables.purchaseOrder');
			Route::get('items/{id}/{jenis}', 'DatatablesController@getItemVariant')->name('datatables.itemVariant');
			Route::get('itemsSO/{id}', 'DatatablesController@getItemShipment')->name('datatables.itemSO');
			Route::get('salesReport', 'DatatablesController@salesReport')->name('datatables.salesReport');
			Route::get('sales/detail/{date}', 'DatatablesController@salesReportDetail')->name('datatables.salesReportDetail');
			Route::get('purchaseReport', 'DatatablesController@purchaseReport')->name('datatables.purchaseReport');
			Route::get('purchase/detail/{date}', 'DatatablesController@purchaseReportDetail')->name('datatables.purchaseReportDetail');
			Route::get('warehouseReport', 'DatatablesController@warehouseReport')->name('datatables.warehouseReport');
			Route::get('returnItems', 'DatatablesController@returnItems')->name('datatables.returnItems');
			Route::get('itemsReturns/{id}', 'DatatablesController@itemsReturn')->name('datatables.itemsReturn');
			/**
			 * Datatable as Service
			 */
			Route::get('invoices/paid', 'InvoicesController@index')->name('datatables.invoicesUnpaid');
			Route::get('invoices/unpaid', 'InvoicesController@getPaid')->name('datatables.invoicesPaid');
			Route::get('salesOrders/approve', 'SalesOrderController@getApproved')->name('datatables.soApproved');
			Route::get('salesOrders/unapprove', 'SalesOrderController@index')->name('datatables.soUnapproved');
			Route::get('shipments/shipped', 'ShipmentController@getApproved')->name('datatables.shipmentApproved');
			Route::get('shipments/unshipped', 'ShipmentController@index')->name('datatables.shipmentUnapproved');
		});
	});
});

core/app/Models/Sales.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Wildside\Userstamps\Userstamps;
use Spatie\Activitylog\Traits\LogsActivity;
use App\Traits\Uuids;
/**
 * Class Sales
 * @package App\Models
 * @version February 17, 2018, 2:33 pm UTC
 *
 * @property string name
 * @property integer tax_included
 * @property integer default_sales_types
 * @property integer created_by
 */
class Sales extends Model
{
    use SoftDeletes;
    use Userstamps;
    use LogsActivity;
    use Uuids;


    public $table = 'sales_types';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';

    protected static $logFillable = true;
    
    const CREATED_BY = 'created_by';
    const UPDATED_BY = 'updated_by';
    const DELETED_BY = 'deleted_by';

    protected $dates = ['deleted_at'];


    public $fillable = [
        'name',
        'tax_included',
        'default',
        'created_by'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'string',
        'name' => 'string',
        'tax_included' => 'integer',
        'default' => 'integer',
        'created_by' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'name' => 'required'
    ];

    public function createdBy()
    {
        return $this->belongsTo('\App\Models\Users', 'created_by', 'id');
    }    
}

core/app/Http/Controllers/Report/SalesController.php
<?php

namespace App\Http\Controllers\Report;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\SalesOrder;
use App\Models\Supplier;
use App\Models\Customer;
use App\Models\PaymentMethod;
use App\Models\Sales;
use DB;
use Auth;

class SalesController extends Controller
{
	public function __construct()
	{
		$data['customers'] = Customer::get();
		$data['payments'] = PaymentMethod::get();
		$data['types'] = Sales::get();
		view()->share($data);
	}

    public function index()
    {
    	$rp = SalesOrder::select(DB::Raw('YEAR(sales_orders.created_at) as year, QUARTER(sales_orders.created_at) as quarter , count(sales_orders.id) as idcount'))->groupBy(DB::raw('YEAR(sales_orders.created_at)',  'QUARTER(sales_orders.created_at)'))->orderByRaw('YEAR(created_at)','QUARTER(created_at)')->get();
    	$data['report_graph'] = $rp;
    	$data['total_sales'] = SalesOrder::get()->count();
    	$data['item_sold'] = SalesOrder::join('sales_order_details', 'sales_orders.id', 'sales_order_details.sales_id')->groupBy('sales_order_details.item_id_variant')->where('status_invoice', '>=' ,1)->get()->count();
    	$data['cost_value'] = rupiah(SalesOrder::selectRaw('sum(amount) as cost_value')->first()->cost_value);
    	$data['percentage'] = (SalesOrder::where( DB::raw('MONTH(created_at)'), '=', date('n') )->get()->count() / 100) * SalesOrder::where(DB::raw('MONTH(created_at)'), '=', date('m'))->get()->count();
    	return view('reports.sales.index', $data);
    }

    public function detail($value='')
    {
    	return view('reports.sales.table', compact('value'));
	}
	
	public function filter(Request $request){
		$input = $request->all();
		if($input['early_date'] !== null && $input['end_date'] !== null){
			$input['date'] = array('early_date' => $input['early_date'], 'end_date' => $input['end_date']);
		}
		unset($input['early_date']);
		unset($input['end_date']);
		$hasil = SalesOrder::filter($input)->get();
		return view('reports.sales.filter', compact('hasil'));
	}
}

core/resources/views/sales/create.blade.php
@extends('layouts.app')
@section('title')
Sales Type
@stop
@section('content')
    <section class="content-header">
        <h1>
            Sales
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-danger">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'salesType.store']) !!}

                        @include('sales.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

core/resources/views/sales/edit.blade.php
@extends('layouts.app')
@section('title')
Sales Type
@stop
@section('content')
    <section class="content-header">
        <h1>
            Sales
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-danger">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($sales, ['route' => ['salesType.update', $sales->id], 'method' => 'patch']) !!}

                        @include('sales.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

core/resources/views/sales/fields.blade.php
@section('css')
<style>
.switch{position:relative;display:inline-block;width:60px;height:34px}.switch input{display:none}.slider{position:absolute;cursor:pointer;top:0;left:0;right:0;bottom:0;background-color:#ccc;-webkit-transition:.4s;transition:.4s}.slider:before{position:absolute;content:"";height:26px;width:26px;left:4px;bottom:4px;background-color:#fff;-webkit-transition:.4s;transition:.4s}input:checked+.slider{background-color:#2196F3}input:focus+.slider{box-shadow:0 0 1px #2196F3}input:checked+.slider:before{-webkit-transform:translateX(26px);-ms-transform:translateX(26px);transform:translateX(26px)}.slider.round{border-radius:34px}.slider.round:before{border-radius:50%}
</style>
@stop
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Tax Included Field -->
<div class="form-group col-sm-6">
    {!! Form::label('tax_included', 'Tax Included:') !!}
    {!! Form::number('tax_included', null, ['class' => 'form-control']) !!}
</div>

<!-- Default Sales Types Field -->
<div class="form-group col-sm-6">
    {!! Form::label('default_sales_types', 'Default Sales Types:') !!}
    <br>
    <!-- Rounded switch -->
    <label class="switch">  
    {!! Form::hidden('default', false) !!}
    {!! Form::checkbox('default', '1', null) !!} 
      <span class="slider round"></span>
    </label>
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('salesType.index') !!}" class="btn btn-default">Cancel</a>
</div>

core/resources/views/sales/index.blade.php
@extends('layouts.app')
@section('title')
Sales Type
@stop
@section('content')
    <section class="content-header">
        <h1 class="pull-left">Sales</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('salesType.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-danger">
            <div class="box-body">
                    @include('sales.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

core/resources/views/sales/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Sales
        </h1>
    </section>
    <div class="content">
        <div class="box box-danger">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('sales.show_fields')
                    <a href="{!! route('salesType.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

core/resources/views/sales/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $sales->id !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $sales->name !!}</p>
</div>

<!-- Tax Included Field -->
<div class="form-group">
    {!! Form::label('tax_included', 'Tax Included:') !!}
    <p>{!! $sales->tax_included !!}</p>
</div>

<!-- Default Sales Types Field -->
<div class="form-group">
    {!! Form::label('default_sales_types', 'Default Sales Types:') !!}
    <p>{!! $sales->default_sales_types !!}</p>
</div>

<!-- Created By Field -->
<div class="form-group">
    {!! Form::label('created_by', 'Created By:') !!}
    <p>{!! $sales->created_by !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $sales->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $sales->updated_at !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $sales->deleted_at !!}</p>
</div>

core/resources/views/sales/table.blade.php
<table class="table table-responsive" id="sales-table">
    <thead>
        <tr>
        <th>Name</th>
        <th>Tax Included</th>
        <th>Default</th>
        <th>Created By</th>
        <th>Action</th>
        </tr>
    </thead>
</table>
@section('scripts')
<script>
$(function() {
    $('#sales-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{!! route('datatables.sales') !!}',
        columns: [
            { data: 'name', name: 'name' },
            { data: 'tax_included', name: 'tax_included' },
            { data: 'default', "render":function(data, type, row){
                if(data == 1){
                    return 'Default';
                }else{
                    return 'Not Default';
                }
            } ,name: 'default' },
            { data: 'created_by.name', name: 'created_by' },
            { data : 'action' ,name:'action'}
        ]
    });
});
</script>
@stop