core/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();


Route::group(['middleware' => 'auth'], function (){
	Route::get('/', 'Frontend\HomeController@index')->name('home');
	Route::get('/customer/cart', 'Frontend\HomeController@index');
	Route::get('/search/query={name}', 'Frontend\HomeController@index');
	Route::get('/{id}', 'Frontend\HomeController@index');
	/**
	 * BACKEND
	 */
	Route::group([ 'prefix' => 'private'], function(){
		Route::get('home', 'HomeController@index')->name('dashboard');
		Route::post('itemsBy', 'ReturnItemController@apiItems')->name('api.itemsBy');
		Route::get('getSku/{id}', 'ItemController@getSku')->name('getSku');
		Route::get('returnItem/approve/{id}', 'ReturnItemController@approve')->name('returnItems.approve');
		Route::get('getAlamat/{cus_id}/{type}', 'SalesOrderController@getAlamat')->name('getAlamat');
		Route::get('downloadCSVex', function(){
			return response()->download(Storage::disk('local')->getDriver()->getAdapter()->getPathPrefix().'/public/[CONTOH MARAVILLOSA].csv');
		})->name('downloadCSVex')->middleware('permission:item');
		Route::resource('warehouseTransfers', 'WarehouseTransferController')->middleware('permission:warehouse-transfer');
		Route::resource('items', 'ItemController')->middleware('permission:item');
		Route::resource('items-variant', 'ItemVariantController')->middleware('permission:item');
		Route::resource('activityLogs', 'ActivityLogController')->middleware('permission:activity-logs');
		Route::resource('returnItems', 'ReturnItemController')->middleware('permission:return-item');
		
		Route::group(['prefix' => 'sales', 'middleware' => 'permission:sales'], function (){
			Route::get('print-invoice/{id}', 'SalesOrderController@printInvoice')->name('print-invoice')->middleware('permission:sales-order');
			Route::get('sales/approve/{id}/{jenis}', 'SalesOrderController@approve')->name('salesOrders.approve')->middleware('permission:sales-order');
			Route::resource('salesOrders', 'SalesOrderController')->middleware('permission:sales-order');
			Route::resource('invoices', 'InvoicesController')->middleware('permission:invoice');
			Route::get('purchase/{id}', 'PurchaseOrderController@approve')->name('purchaseOrders.approve')->middleware('permission:purchase-order');
			Route::resource('purchaseOrders', 'PurchaseOrderController')->middleware('permission:purchase-order');
			Route::resource('shipments', 'ShipmentController')->middleware('permission:shipment');
			Route::get('shipments/create/{id}', 'ShipmentController@create')->name('shipments.buat')->middleware('permission:shipment');
			Route::get('shipments/approve/{id}', 'ShipmentController@approve')->name('shipments.approve')->middleware('permission:shipment');
		});
		
		Route::group(['prefix' => 'report', 'namespace' => 'Report', 'middleware' => 'permission:reports'], function (){
			Route::get('purchase', 'PurchaseController@index')->name('report.purchase')->middleware('permission:report-purchase');
			Route::get('purchase/detail/{date}', 'PurchaseController@detail')->name('report.purchase.detail')->middleware('permission:report-purchase');
			Route::get('sales', 'SalesController@index')->name('report.sales')->middleware('permission:report-sales');
			Route::get('sales/detail/{date}', 'SalesController@detail')->name('report.sales.detail')->middleware('permission:report-sales');
			Route::get('warehouses', 'WarehousesController@index')->name('report.warehouses')->middleware('permission:report-stock');
			/**	FILTER */
			Route::post('purchase/filter', 'PurchaseController@filter')->name('filter.purchase')->middleware('permission:report-purchase');
			Route::post('sales/filter', 'SalesController@filter')->name('filter.sales')->middleware('permission:report-sales');
			Route::post('warehouses/filter', 'WarehousesController@filter')->name('filter.item')->middleware('permission:report-stock');
			Route::get('item/find', 'WarehousesController@apiNamaBarang')->name('api.findNamaBarang')->middleware('permission:report-stock');
			Route::post('item/find/variant', 'WarehousesController@apiNamaVariant')->name('api.findNamaVariant')->middleware('permission:report-stock');
		});
		
		Route::group(['prefix' => 'setting', 'middleware'=> ['permission:settings']], function (){
			Route::resource('users', 'UsersController')->middleware('permission:users');
			Route::resource('warehouses', 'WarehouseController')->middleware('permission:warehouses');
			Route::resource('brands', 'BrandController')->middleware('permission:brands');
			Route::resource('categories', 'CategoryController')->middleware('permission:categories');
			Route::resource('salesType', 'SalesTypeController')->middleware('permission:sales-type');
			Route::resource('suplliers', 'SupllierController')->middleware('permission:suppliers');
			Route::resource('customers', 'CustomerController')->middleware('permission:customers');
			Route::resource('paymentMethods', 'PaymentMethodController')->middleware('permission:payment-methods');
			Route::resource('taxes', 'TaxController')->middleware('permission:taxes');
			Route::resource('permissions', 'PermissionController')->middleware('permission:permissions');
			Route::resource('roles', 'RolesController')->middleware('permission:roles');
			Route::resource('departments', 'DepartmentController');
			Route::resource('satuans', 'SatuanController');
			Route::resource('itemVariants', 'ItemVariantController');
		});
		
		Route::group(['prefix' => 'datatables'], function(){
			Route::get('user', 'DatatablesController@getUsers')->name('datatables.users');
			Route::get('warehouses', 'DatatablesController@getWarehouses')->name('datatables.warehouses');
			Route::get('brands', 'DatatablesController@getBrands')->name('datatables.brands');
			Route::get('categories', 'DatatablesController@getCategories')->name('datatables.categories');
			Route::get('sales', 'DatatablesController@getSales')->name('datatables.sales');
			Route::get('suplliers', 'DatatablesController@getSuplliers')->name('datatables.suplliers');
			Route::get('customers', 'DatatablesController@getCustomers')->name('datatables.customers');
			Route::get('items', 'DatatablesController@getItems')->name('datatables.items');
			Route::get('itemsSales', 'DatatablesController@getItemsSales')->name('datatables.itemsSales');
			Route::get('itemsPurchase', 'DatatablesController@getItemsPurchase')->name('datatables.itemsPurchase');
			Route::get('salesOrders', 'DatatablesController@getSalesOrders')->name('datatables.salesOrders');
			Route::get('paymentMethods', 'DatatablesController@getPaymentMethods')->name('datatables.paymentMethods');
			Route::get('warehouseTransfer', 'DatatablesController@getWarehouseTransfer')->name('datatables.warehouseTransfer');
			Route::get('itemsWT', 'DatatablesController@getItemsWT')->name('datatables.itemsWT');
			Route::get('logs', 'DatatablesController@getActivityLog')->name('datatables.logs');
			Route::get('purchaseOrder', 'DatatablesController@getPurchaseOrders')->name('datatables.purchaseOrder');
			Route::get('items/{id}/{jenis}', 'DatatablesController@getItemVariant')->name('datatables.itemVariant');
			Route::get('itemsSO/{id}', 'DatatablesController@getItemShipment')->name('datatables.itemSO');
			Route::get('salesReport', 'DatatablesController@salesReport')->name('datatables.salesReport');
			Route::get('sales/detail/{date}', 'DatatablesController@salesReportDetail')->name('datatables.salesReportDetail');
			Route::get('purchaseReport', 'DatatablesController@purchaseReport')->name('datatables.purchaseReport');
			Route::get('purchase/detail/{date}', 'DatatablesController@purchaseReportDetail')->name('datatables.purchaseReportDetail');
			Route::get('warehouseReport', 'DatatablesController@warehouseReport')->name('datatables.warehouseReport');
			Route::get('returnItems', 'DatatablesController@returnItems')->name('datatables.returnItems');
			Route::get('itemsReturns/{id}', 'DatatablesController@itemsReturn')->name('datatables.itemsReturn');
			/**
			 * Datatable as Service
			 */
			Route::get('invoices/paid', 'InvoicesController@index')->name('datatables.invoicesUnpaid');
			Route::get('invoices/unpaid', 'InvoicesController@getPaid')->name('datatables.invoicesPaid');
			Route::get('salesOrders/approve', 'SalesOrderController@getApproved')->name('datatables.soApproved');
			Route::get('salesOrders/unapprove', 'SalesOrderController@index')->name('datatables.soUnapproved');
			Route::get('shipments/shipped', 'ShipmentController@getApproved')->name('datatables.shipmentApproved');
			Route::get('shipments/unshipped', 'ShipmentController@index')->name('datatables.shipmentUnapproved');
		});
	});
});

core/app/Models/Warehouse.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Wildside\Userstamps\Userstamps;
use Spatie\Activitylog\Traits\LogsActivity;
use App\Traits\Uuids;
/**
 * Class Warehouse
 * @package App\Models
 * @version February 17, 2018, 2:26 pm UTC
 *
 * @property integer id
 * @property string name
 * @property boolean default
 * @property integer created_by
 */
class Warehouse extends Model
{
    use SoftDeletes;
    use Userstamps;
    use LogsActivity;
    use Uuids;
    
    public $table = 'warehouses';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';

    protected static $logFillable = true;
    
    const CREATED_BY = 'created_by';
    const UPDATED_BY = 'updated_by';
    const DELETED_BY = 'deleted_by';

    protected $dates = ['deleted_at'];

    public $fillable = [
        'id',
        'name',
        'default',
        'created_by'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'string',
        'name' => 'string',
        'default' => 'boolean',
        'created_by' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'name' => 'required'
    ];
   
   public function detailVariant()
   {
       return $this->belongsTo('\App\Models\ItemVariant', 'warehouse');
   }

    public function createdBy()
    {
        return $this->belongsTo('\App\Models\Users', 'created_by', 'id');
    }
}

core/app/Http/Controllers/Report/PurchaseController.php
<?php

namespace App\Http\Controllers\Report;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\PurchaseOrder;
use DB;
use Auth;
use App\Models\Supllier;
use App\Models\PaymentMethod;
class PurchaseController extends Controller
{	
	public function __construct()
	{
		$data['suppliers'] = Supllier::get();
		$data['payments'] = PaymentMethod::get();
		view()->share($data);
	}
  	public function index()
    {
    	$rp = PurchaseOrder::select(DB::Raw('YEAR(purchase_order.created_at) as year, QUARTER(purchase_order.created_at) as quarter , count(purchase_order.id) as idcount'))->groupBy(DB::raw('YEAR(purchase_order.created_at)',  'QUARTER(purchase_order.created_at)'))->orderByRaw('YEAR(created_at)','QUARTER(created_at)')->get();
    	$data['report_graph'] = $rp;
    	$data['total_sales'] = PurchaseOrder::get()->count();
    	$data['item_sold'] = PurchaseOrder::join('purchase_order_details', 'purchase_order.id', 'purchase_order_details.purchase_order_id')->groupBy('purchase_order_details.item_id_variant')->get()->count();
    	$data['cost_value'] = rupiah(PurchaseOrder::selectRaw('sum(amount) as cost_value')->first()->cost_value);
    	$data['percentage'] = (PurchaseOrder::where( DB::raw('MONTH(created_at)'), '=', date('n') )->get()->count() / 100) * PurchaseOrder::where(DB::raw('MONTH(created_at)'), '=', date('m'))->get()->count();
    	return view('reports.purchase.index', $data);
    }

    public function detail($value='')
    {
    	return view('reports.purchase.table', compact('value'));
	}
	
	public function filter(Request $request){
		$input = $request->all();
		if($input['early_date'] !== null && $input['end_date'] !== null){
			$input['date'] = array('early_date' => $input['early_date'], 'end_date' => $input['end_date']);
		}
		unset($input['early_date']);
		unset($input['end_date']);
		$hasil = PurchaseOrder::filter($input)->get();
		return view('reports.purchase.filter', compact('hasil'));
	}
}

core/app/Http/Controllers/Report/SalesController.php
<?php

namespace App\Http\Controllers\Report;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\SalesOrder;
use App\Models\Supplier;
use App\Models\Customer;
use App\Models\PaymentMethod;
use App\Models\Sales;
use DB;
use Auth;

class SalesController extends Controller
{
	public function __construct()
	{
		$data['customers'] = Customer::get();
		$data['payments'] = PaymentMethod::get();
		$data['types'] = Sales::get();
		view()->share($data);
	}

    public function index()
    {
    	$rp = SalesOrder::select(DB::Raw('YEAR(sales_orders.created_at) as year, QUARTER(sales_orders.created_at) as quarter , count(sales_orders.id) as idcount'))->groupBy(DB::raw('YEAR(sales_orders.created_at)',  'QUARTER(sales_orders.created_at)'))->orderByRaw('YEAR(created_at)','QUARTER(created_at)')->get();
    	$data['report_graph'] = $rp;
    	$data['total_sales'] = SalesOrder::get()->count();
    	$data['item_sold'] = SalesOrder::join('sales_order_details', 'sales_orders.id', 'sales_order_details.sales_id')->groupBy('sales_order_details.item_id_variant')->where('status_invoice', '>=' ,1)->get()->count();
    	$data['cost_value'] = rupiah(SalesOrder::selectRaw('sum(amount) as cost_value')->first()->cost_value);
    	$data['percentage'] = (SalesOrder::where( DB::raw('MONTH(created_at)'), '=', date('n') )->get()->count() / 100) * SalesOrder::where(DB::raw('MONTH(created_at)'), '=', date('m'))->get()->count();
    	return view('reports.sales.index', $data);
    }

    public function detail($value='')
    {
    	return view('reports.sales.table', compact('value'));
	}
	
	public function filter(Request $request){
		$input = $request->all();
		if($input['early_date'] !== null && $input['end_date'] !== null){
			$input['date'] = array('early_date' => $input['early_date'], 'end_date' => $input['end_date']);
		}
		unset($input['early_date']);
		unset($input['end_date']);
		$hasil = SalesOrder::filter($input)->get();
		return view('reports.sales.filter', compact('hasil'));
	}
}

core/app/Http/Controllers/Report/WarehousesController.php
<?php

namespace App\Http\Controllers\Report;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\ItemVariant;
use App\Models\Item;
use App\Models\Category;
use App\Models\Brand;
use App\Models\Warehouse;
use App\Models\Department;
use DB;

class WarehousesController extends Controller
{
	public function __construct(){
		$data['brands'] = Brand::get();
		$data['categories'] = Category::get();
		$data['warehouses'] = Warehouse::get();
		$data['departments'] = Department::get();
		view()->share($data);
	}

     public function index()
    {
    	$data['report_graph'] = Item::join('item_variant', 'items.id', 'item_variant.item_id')->join('warehouses', 'item_variant.warehouse','warehouses.id')->select(DB::raw('items.name, sum(item_variant.value) as qtyItem, warehouses.name as whName'))->groupBy('item_variant.item_id')->get();
    	$data['item_stock'] = array_sum(ItemVariant::join('warehouses', 'item_variant.warehouse', 'warehouses.id')->groupBy('item_variant.item_id', 'item_variant.id')->select(DB::raw('sum(item_variant.value) as item_stock'))->pluck('item_stock')->toArray());
    	$data['cost_value'] = rupiah(ItemVariant::selectRaw('sum(price*value) as cost_value')->first()->cost_value);
    	return view('reports.warehouse.index', $data);
    }

    public function detail($value='')
    {
    	return view('reports.warehouse.table', compact('value'));
    }

    public function filter(Request $request){
		$input = $request->all();
		$data = Item::filter($input)->get();
		return view('reports.warehouse.filter', compact('data'));
	}

	public function apiNamaBarang(){
		$item = Item::filter(array('name' => request()->get('q')))->get();
		return response()->json($item);
	}

	public function apiNamaVariant(){
		$id = Item::where('name', request()->id)->first()->id;
		$items = ItemVariant::where('item_id', $id)->groupBy('id_variant')->get();
		$option = "<option value>-Pilih Variant-</option>";
		foreach($items as $item){
			$option.='<option value="'.$item->id.'">'.$item->warna.' '.$item->pattern.' '.$item->size.' '.$item->roll.'</option>';
		}
		return $option;
	}
}

core/resources/views/reports/warehouse/addFilter.blade.php
<aside class="control-sidebar control-sidebar-dark" id="sidebar-filter">
    <div class="tab-content">
      <div class="tab-pane active" id="control-sidebar-home-tab">
        <form class="form-inline" action="{{route('filter.item')}}" method="POST">
        {{csrf_field()}}
          <div class="row">
            <div class="form-group col-lg-12">
              <h4>Item Filter</h4>
            </div>
            <div class="form-group  col-lg-12">
                <label>Nama Barang</label>
                <select name="name" class="cari form-control"><select>
            </div>
            <div class="form-group col-lg-12">
                <label>Variant</label>
                <select name="variant" id="variant" class="form-control"></select>
            </div>
            <div class="form-group col-lg-12">
              <label>Brand</label>
              <select class="select2 form-control" name="brand">
                <option value="">-Pilih Brand-</option>
                @foreach($brands as $brand)
                <option value="{{$brand->id}}">{{$brand->brand_name}}</option>
                @endforeach
              </select>
            </div>
            <div class="form-group col-lg-12">
              <label>Category</label>
              <select class="select2 form-control" name="category">
                <option value="">-Pilih Category-</option>
                @foreach($categories as $category)
                <option value="{{$category->id}}">{{$category->name}}</option>
                @endforeach
              </select>
            </div>
            <div class="form-group col-lg-12">
              <label>Warehouse</label>
              <select class="select2 form-control" name="warehouse">
                <option value="">-Pilih Warehouse-</option>
                 @foreach($warehouses as $warehouse)
                <option value="{{$warehouse->id}}">{{$warehouse->name}}</option>
                @endforeach
              </select>
            </div>
            <div class="form-group col-lg-12">
              <label>Department</label>
              <select class="select2 form-control" name="department">
                <option value="">-Pilih Deparment-</option>
                 @foreach($departments as $department)
                <option value="{{$department->id}}">{{$department->name}}</option>
                @endforeach
              </select>
            </div>
            <div class="form-group col-lg-12">
              <input type="submit" class="btn btn-info" value="Submit"/>
              <a href="#" class="btn btn-default filter" data-toggle="control-sidebar">Batal</a>
            </div>
          </div>
       </form>
      </div>
    </div>
</aside> 
@push('scripts')
<script>
$(".cari").select2({
  placeholder : 'Mencari...',
  ajax: {
    url: "{{route('api.findNamaBarang')}}",
    dataType: 'json',
    delay: 250,
    processResults: function (data) {
      return {
        results:  $.map(data, function (item) {
          return {
            text: item.name,
            id: item.name
          }
        })
      };
    },
    cache: true
  }
});
$('.cari').on('change', function() {
  var data = $(".cari option:selected").val();
  $.post("{{route('api.findNamaVariant')}}", {_token : $('meta[name="csrf-token"]').attr('content'), id:data}, function(data){
    $("#variant").html(data);
    $("#variant").select2();
  });
});
$(".content-wrapper").click(function(e) 
{
    var container = $("#sidebar-filter");
    if(!container.is(e.target) && container.has(e.target).length === 0 && !$(e.target).hasClass('filter'))
    {
        $(container).attr('class', 'control-sidebar control-sidebar-dark');
    }
});
</script>
@endpush

core/resources/views/reports/warehouse/filter.blade.php
@extends('layouts.app')
@section('content')
<section class="content-header">
    <h1>
    Warehouse
    <small>Report Warehouse</small>
    <div class="pull-right">
        <a href="#" class="btn btn-success filter" data-toggle="control-sidebar">Filter</a>
    </div>
    </h1>
</section>
<div class="content">
    <div class="clearfix"></div>
    <div class="box box-danger">
        <div class="box-body">
            <table class="table table-responsive" id="sales-table">
                <thead>
                    <tr>
                        <th>Reference</th>
                        <th>Variant</th>
                        <th>Brand</th>
                        <th>Category</th>
                    </tr>
                </thead>
                <tbody>
                    <?php $all = 0 ?>
                    @foreach($data as $index => $data)
                    <tr>
                        <td><a href="{{route('items.show', $data->id)}}">{{$data->name}}</a></td>
                        <td>{{getVariant($data->variant)}}</td>
                        <td>{{$data->brands->brand_name}}</td>
                        <td>{{$data->categories->name}}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@include('reports.warehouse.addFilter')
@stop
@section('scripts')
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.1/css/buttons.dataTables.min.css">
<script src="https://cdn.datatables.net/buttons/1.5.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.html5.min.js"></script>
<script type="text/javascript">
$(function() {
    $('#sales-table').DataTable({
        dom : 'Blfrtip',
        buttons: [
            'pdfHtml5', 'excelHtml5'
        ]
    });
});
</script>
@stop

core/resources/views/reports/warehouse/index.blade.php
@extends('layouts.app')
@section('title', 'Report Warehouse '.date("Y-m-d"))
@section('content')
<section class="content-header">
 <h1>
    Warehouse
    <small>Report Warehouse </small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Warehouse</li>
  </ol>
</section>
<div class="content">
	<section class="connectedSortable ui-sortable">
		<div class="box box-solid bg-info" style="position: relative;left: 0px;top: 0px;">
			<div class="box-header ui-sortable-handle" style="cursor: move;">
				<h3 class="box-title" style="color: #303030">Stock Warehouse</h3>
				<div class="box-tools pull-right">
					<button type="button" class="btn bg-re btn-sm" data-widget="collapse"><i class="fa fa-minus"></i>
					</button>
				</div>
			</div>
			<div class="box-body border-radius-none">
				<div class="chart" id="bar-chart" style="height: 250px;">
					
				</div>
			</div>
		</div>
	</section>
	<div class="row">
      <div class="col-lg-3 col-xs-6" >
        <!-- small box -->
        <div class="small-box bg-green"  style="min-height: 128px;">
          <div class="inner">
            <h3>{{$item_stock}}</h3>

            <p>Items Stock</p>
          </div>
          <div class="icon">
            <i class="ion ion-bag"></i>
          </div>
          <!-- <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a> -->
        </div>
      </div>
      <div class="col-lg-3 col-xs-6">
        <div class="small-box bg-yellow" style="min-height: 128px;">
            <div class="inner">
              <h3 style="font-size: 24px;">{{$cost_value}}</h3>
              <p>Cost Value</p>
            </div>
            <div class="icon">
              <i class="ion ion-cash"></i>
            </div>
          <!-- <a href="#" class="small-box-footer" style="margin-top: auto;">More info <i class="fa fa-arrow-circle-right"></i></a> -->
        	</div>
      </div>
	</div>
	<div class="box box-solid">
		<div class="box-header ui-sortable-handle" style="cursor: move;">
			<h3 class="box-title">Warehouse</h3>
			<div class="box-tools pull-right">
			<a href="#" class="btn btn-success filter" data-toggle="control-sidebar">Filter</a>
			</div>
		</div>
		<div class="box-body border-radius-none">
			<table class="table table-responsive" id="salesOrders-table">
			    <thead>
			        <tr>
			        <th>Item</th>
			        <th>Variant</th>
			        <th>Stock</th>
			        </tr>
			    </thead>
			</table>
		</div>
	</div>
</div>
@include('reports.warehouse.addFilter')
@stop
@section('scripts')
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.1/css/buttons.dataTables.min.css">
<script src="https://cdn.datatables.net/buttons/1.5.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.html5.min.js"></script>
<script type="text/javascript">
$(function() {
    $('#salesOrders-table').DataTable({
        processing: true,
        serverSide: true,
        dom : 'Blfrtip',
        buttons: [
          'excelHtml5', 'pdfHtml5'
        ],
        ajax: '{!! route('datatables.warehouseReport') !!}',
        columns: [
            { data: 'action', name: 'action'},
            { data: 'variant', render:function(data, type, row){
                var good = decodeHTMLEntities(data.replace(/[0-9]/g, '')).replace(/\W/g, '');
                
                if(good == 'cpsr'){
                    return 'Warna, Pattern, Size, Roll';
                }else if(good = 'cps'){
                    return 'Warna, Pattern, Size';
                }else if(good = 'cp'){
                    return 'Warna, Pattern';
                }else{
                    return 'Warna';
                }
            } , name: 'variant' },
            { data: 'value',name: 'value' }
        ]
    });
});
var line = new Morris.Bar({
    element          : 'bar-chart',
    resize           : true,
    data             : [
    @foreach($report_graph as $val)
      { item : '{{$val->name}}', a : {{$val->qtyItem}} },
    @endforeach
    ],
    xkey             : 'item',
    ykeys            : ['a'],
    labels           : ['Total Stock(s)'],
    lineColors       : ['#303030'],
    lineWidth        : 2,
    hideHover        : 'auto',
    gridTextColor    : '#303030',
    gridStrokeWidth  : 0.4,
    pointSize        : 4,
    pointStrokeColors: ['#00a65a'],
    gridLineColor    : '#00a65a',
    gridTextFamily   : ['Source Sans Pro','Helvetica Neue','Helvetica,Arial,sans-serif'],
    gridTextSize     : 13
  });
</script>
@stop