core/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();


Route::group(['middleware' => 'auth'], function (){
	Route::get('/', 'Frontend\HomeController@index')->name('home');
	Route::get('/customer/cart', 'Frontend\HomeController@index');
	Route::get('/search/query={name}', 'Frontend\HomeController@index');
	Route::get('/{id}', 'Frontend\HomeController@index');
	/**
	 * BACKEND
	 */
	Route::group([ 'prefix' => 'private'], function(){
		Route::get('home', 'HomeController@index')->name('dashboard');
		Route::post('itemsBy', 'ReturnItemController@apiItems')->name('api.itemsBy');
		Route::get('getSku/{id}', 'ItemController@getSku')->name('getSku');
		Route::get('returnItem/approve/{id}', 'ReturnItemController@approve')->name('returnItems.approve');
		Route::get('getAlamat/{cus_id}/{type}', 'SalesOrderController@getAlamat')->name('getAlamat');
		Route::get('downloadCSVex', function(){
			return response()->download(Storage::disk('local')->getDriver()->getAdapter()->getPathPrefix().'/public/[CONTOH MARAVILLOSA].csv');
		})->name('downloadCSVex')->middleware('permission:item');
		Route::resource('warehouseTransfers', 'WarehouseTransferController')->middleware('permission:warehouse-transfer');
		Route::resource('items', 'ItemController')->middleware('permission:item');
		Route::resource('items-variant', 'ItemVariantController')->middleware('permission:item');
		Route::resource('activityLogs', 'ActivityLogController')->middleware('permission:activity-logs');
		Route::resource('returnItems', 'ReturnItemController')->middleware('permission:return-item');
		
		Route::group(['prefix' => 'sales', 'middleware' => 'permission:sales'], function (){
			Route::get('print-invoice/{id}', 'SalesOrderController@printInvoice')->name('print-invoice')->middleware('permission:sales-order');
			Route::get('sales/approve/{id}/{jenis}', 'SalesOrderController@approve')->name('salesOrders.approve')->middleware('permission:sales-order');
			Route::resource('salesOrders', 'SalesOrderController')->middleware('permission:sales-order');
			Route::resource('invoices', 'InvoicesController')->middleware('permission:invoice');
			Route::get('purchase/{id}', 'PurchaseOrderController@approve')->name('purchaseOrders.approve')->middleware('permission:purchase-order');
			Route::resource('purchaseOrders', 'PurchaseOrderController')->middleware('permission:purchase-order');
			Route::resource('shipments', 'ShipmentController')->middleware('permission:shipment');
			Route::get('shipments/create/{id}', 'ShipmentController@create')->name('shipments.buat')->middleware('permission:shipment');
			Route::get('shipments/approve/{id}', 'ShipmentController@approve')->name('shipments.approve')->middleware('permission:shipment');
		});
		
		Route::group(['prefix' => 'report', 'namespace' => 'Report', 'middleware' => 'permission:reports'], function (){
			Route::get('purchase', 'PurchaseController@index')->name('report.purchase')->middleware('permission:report-purchase');
			Route::get('purchase/detail/{date}', 'PurchaseController@detail')->name('report.purchase.detail')->middleware('permission:report-purchase');
			Route::get('sales', 'SalesController@index')->name('report.sales')->middleware('permission:report-sales');
			Route::get('sales/detail/{date}', 'SalesController@detail')->name('report.sales.detail')->middleware('permission:report-sales');
			Route::get('warehouses', 'WarehousesController@index')->name('report.warehouses')->middleware('permission:report-stock');
			/**	FILTER */
			Route::post('purchase/filter', 'PurchaseController@filter')->name('filter.purchase')->middleware('permission:report-purchase');
			Route::post('sales/filter', 'SalesController@filter')->name('filter.sales')->middleware('permission:report-sales');
			Route::post('warehouses/filter', 'WarehousesController@filter')->name('filter.item')->middleware('permission:report-stock');
			Route::get('item/find', 'WarehousesController@apiNamaBarang')->name('api.findNamaBarang')->middleware('permission:report-stock');
			Route::post('item/find/variant', 'WarehousesController@apiNamaVariant')->name('api.findNamaVariant')->middleware('permission:report-stock');
		});
		
		Route::group(['prefix' => 'setting', 'middleware'=> ['permission:settings']], function (){
			Route::resource('users', 'UsersController')->middleware('permission:users');
			Route::resource('warehouses', 'WarehouseController')->middleware('permission:warehouses');
			Route::resource('brands', 'BrandController')->middleware('permission:brands');
			Route::resource('categories', 'CategoryController')->middleware('permission:categories');
			Route::resource('salesType', 'SalesTypeController')->middleware('permission:sales-type');
			Route::resource('suplliers', 'SupllierController')->middleware('permission:suppliers');
			Route::resource('customers', 'CustomerController')->middleware('permission:customers');
			Route::resource('paymentMethods', 'PaymentMethodController')->middleware('permission:payment-methods');
			Route::resource('taxes', 'TaxController')->middleware('permission:taxes');
			Route::resource('permissions', 'PermissionController')->middleware('permission:permissions');
			Route::resource('roles', 'RolesController')->middleware('permission:roles');
			Route::resource('departments', 'DepartmentController');
			Route::resource('satuans', 'SatuanController');
			Route::resource('itemVariants', 'ItemVariantController');
		});
		
		Route::group(['prefix' => 'datatables'], function(){
			Route::get('user', 'DatatablesController@getUsers')->name('datatables.users');
			Route::get('warehouses', 'DatatablesController@getWarehouses')->name('datatables.warehouses');
			Route::get('brands', 'DatatablesController@getBrands')->name('datatables.brands');
			Route::get('categories', 'DatatablesController@getCategories')->name('datatables.categories');
			Route::get('sales', 'DatatablesController@getSales')->name('datatables.sales');
			Route::get('suplliers', 'DatatablesController@getSuplliers')->name('datatables.suplliers');
			Route::get('customers', 'DatatablesController@getCustomers')->name('datatables.customers');
			Route::get('items', 'DatatablesController@getItems')->name('datatables.items');
			Route::get('itemsSales', 'DatatablesController@getItemsSales')->name('datatables.itemsSales');
			Route::get('itemsPurchase', 'DatatablesController@getItemsPurchase')->name('datatables.itemsPurchase');
			Route::get('salesOrders', 'DatatablesController@getSalesOrders')->name('datatables.salesOrders');
			Route::get('paymentMethods', 'DatatablesController@getPaymentMethods')->name('datatables.paymentMethods');
			Route::get('warehouseTransfer', 'DatatablesController@getWarehouseTransfer')->name('datatables.warehouseTransfer');
			Route::get('itemsWT', 'DatatablesController@getItemsWT')->name('datatables.itemsWT');
			Route::get('logs', 'DatatablesController@getActivityLog')->name('datatables.logs');
			Route::get('purchaseOrder', 'DatatablesController@getPurchaseOrders')->name('datatables.purchaseOrder');
			Route::get('items/{id}/{jenis}', 'DatatablesController@getItemVariant')->name('datatables.itemVariant');
			Route::get('itemsSO/{id}', 'DatatablesController@getItemShipment')->name('datatables.itemSO');
			Route::get('salesReport', 'DatatablesController@salesReport')->name('datatables.salesReport');
			Route::get('sales/detail/{date}', 'DatatablesController@salesReportDetail')->name('datatables.salesReportDetail');
			Route::get('purchaseReport', 'DatatablesController@purchaseReport')->name('datatables.purchaseReport');
			Route::get('purchase/detail/{date}', 'DatatablesController@purchaseReportDetail')->name('datatables.purchaseReportDetail');
			Route::get('warehouseReport', 'DatatablesController@warehouseReport')->name('datatables.warehouseReport');
			Route::get('returnItems', 'DatatablesController@returnItems')->name('datatables.returnItems');
			Route::get('itemsReturns/{id}', 'DatatablesController@itemsReturn')->name('datatables.itemsReturn');
			/**
			 * Datatable as Service
			 */
			Route::get('invoices/paid', 'InvoicesController@index')->name('datatables.invoicesUnpaid');
			Route::get('invoices/unpaid', 'InvoicesController@getPaid')->name('datatables.invoicesPaid');
			Route::get('salesOrders/approve', 'SalesOrderController@getApproved')->name('datatables.soApproved');
			Route::get('salesOrders/unapprove', 'SalesOrderController@index')->name('datatables.soUnapproved');
			Route::get('shipments/shipped', 'ShipmentController@getApproved')->name('datatables.shipmentApproved');
			Route::get('shipments/unshipped', 'ShipmentController@index')->name('datatables.shipmentUnapproved');
		});
	});
});

core/app/Http/Controllers/Report/PurchaseController.php
<?php

namespace App\Http\Controllers\Report;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\PurchaseOrder;
use DB;
use Auth;
use App\Models\Supllier;
use App\Models\PaymentMethod;
class PurchaseController extends Controller
{	
	public function __construct()
	{
		$data['suppliers'] = Supllier::get();
		$data['payments'] = PaymentMethod::get();
		view()->share($data);
	}
  	public function index()
    {
    	$rp = PurchaseOrder::select(DB::Raw('YEAR(purchase_order.created_at) as year, QUARTER(purchase_order.created_at) as quarter , count(purchase_order.id) as idcount'))->groupBy(DB::raw('YEAR(purchase_order.created_at)',  'QUARTER(purchase_order.created_at)'))->orderByRaw('YEAR(created_at)','QUARTER(created_at)')->get();
    	$data['report_graph'] = $rp;
    	$data['total_sales'] = PurchaseOrder::get()->count();
    	$data['item_sold'] = PurchaseOrder::join('purchase_order_details', 'purchase_order.id', 'purchase_order_details.purchase_order_id')->groupBy('purchase_order_details.item_id_variant')->get()->count();
    	$data['cost_value'] = rupiah(PurchaseOrder::selectRaw('sum(amount) as cost_value')->first()->cost_value);
    	$data['percentage'] = (PurchaseOrder::where( DB::raw('MONTH(created_at)'), '=', date('n') )->get()->count() / 100) * PurchaseOrder::where(DB::raw('MONTH(created_at)'), '=', date('m'))->get()->count();
    	return view('reports.purchase.index', $data);
    }

    public function detail($value='')
    {
    	return view('reports.purchase.table', compact('value'));
	}
	
	public function filter(Request $request){
		$input = $request->all();
		if($input['early_date'] !== null && $input['end_date'] !== null){
			$input['date'] = array('early_date' => $input['early_date'], 'end_date' => $input['end_date']);
		}
		unset($input['early_date']);
		unset($input['end_date']);
		$hasil = PurchaseOrder::filter($input)->get();
		return view('reports.purchase.filter', compact('hasil'));
	}
}

core/app/Http/Controllers/Report/SalesController.php
<?php

namespace App\Http\Controllers\Report;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\SalesOrder;
use App\Models\Supplier;
use App\Models\Customer;
use App\Models\PaymentMethod;
use App\Models\Sales;
use DB;
use Auth;

class SalesController extends Controller
{
	public function __construct()
	{
		$data['customers'] = Customer::get();
		$data['payments'] = PaymentMethod::get();
		$data['types'] = Sales::get();
		view()->share($data);
	}

    public function index()
    {
    	$rp = SalesOrder::select(DB::Raw('YEAR(sales_orders.created_at) as year, QUARTER(sales_orders.created_at) as quarter , count(sales_orders.id) as idcount'))->groupBy(DB::raw('YEAR(sales_orders.created_at)',  'QUARTER(sales_orders.created_at)'))->orderByRaw('YEAR(created_at)','QUARTER(created_at)')->get();
    	$data['report_graph'] = $rp;
    	$data['total_sales'] = SalesOrder::get()->count();
    	$data['item_sold'] = SalesOrder::join('sales_order_details', 'sales_orders.id', 'sales_order_details.sales_id')->groupBy('sales_order_details.item_id_variant')->where('status_invoice', '>=' ,1)->get()->count();
    	$data['cost_value'] = rupiah(SalesOrder::selectRaw('sum(amount) as cost_value')->first()->cost_value);
    	$data['percentage'] = (SalesOrder::where( DB::raw('MONTH(created_at)'), '=', date('n') )->get()->count() / 100) * SalesOrder::where(DB::raw('MONTH(created_at)'), '=', date('m'))->get()->count();
    	return view('reports.sales.index', $data);
    }

    public function detail($value='')
    {
    	return view('reports.sales.table', compact('value'));
	}
	
	public function filter(Request $request){
		$input = $request->all();
		if($input['early_date'] !== null && $input['end_date'] !== null){
			$input['date'] = array('early_date' => $input['early_date'], 'end_date' => $input['end_date']);
		}
		unset($input['early_date']);
		unset($input['end_date']);
		$hasil = SalesOrder::filter($input)->get();
		return view('reports.sales.filter', compact('hasil'));
	}
}

core/app/Http/Controllers/Report/WarehousesController.php
<?php

namespace App\Http\Controllers\Report;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\ItemVariant;
use App\Models\Item;
use App\Models\Category;
use App\Models\Brand;
use App\Models\Warehouse;
use App\Models\Department;
use DB;

class WarehousesController extends Controller
{
	public function __construct(){
		$data['brands'] = Brand::get();
		$data['categories'] = Category::get();
		$data['warehouses'] = Warehouse::get();
		$data['departments'] = Department::get();
		view()->share($data);
	}

     public function index()
    {
    	$data['report_graph'] = Item::join('item_variant', 'items.id', 'item_variant.item_id')->join('warehouses', 'item_variant.warehouse','warehouses.id')->select(DB::raw('items.name, sum(item_variant.value) as qtyItem, warehouses.name as whName'))->groupBy('item_variant.item_id')->get();
    	$data['item_stock'] = array_sum(ItemVariant::join('warehouses', 'item_variant.warehouse', 'warehouses.id')->groupBy('item_variant.item_id', 'item_variant.id')->select(DB::raw('sum(item_variant.value) as item_stock'))->pluck('item_stock')->toArray());
    	$data['cost_value'] = rupiah(ItemVariant::selectRaw('sum(price*value) as cost_value')->first()->cost_value);
    	return view('reports.warehouse.index', $data);
    }

    public function detail($value='')
    {
    	return view('reports.warehouse.table', compact('value'));
    }

    public function filter(Request $request){
		$input = $request->all();
		$data = Item::filter($input)->get();
		return view('reports.warehouse.filter', compact('data'));
	}

	public function apiNamaBarang(){
		$item = Item::filter(array('name' => request()->get('q')))->get();
		return response()->json($item);
	}

	public function apiNamaVariant(){
		$id = Item::where('name', request()->id)->first()->id;
		$items = ItemVariant::where('item_id', $id)->groupBy('id_variant')->get();
		$option = "<option value>-Pilih Variant-</option>";
		foreach($items as $item){
			$option.='<option value="'.$item->id.'">'.$item->warna.' '.$item->pattern.' '.$item->size.' '.$item->roll.'</option>';
		}
		return $option;
	}
}

core/resources/views/reports/purchase/addFilter.blade.php
<aside class="control-sidebar control-sidebar-dark" id="sidebar-filter">
    <div class="tab-content">
      <div class="tab-pane active" id="control-sidebar-home-tab">
        <form class="form-inline" action="{{route('filter.purchase')}}" method="POST">
        {{csrf_field()}}
          <div class="row">
            <div class="form-group col-lg-12">
              <h4>Purchase Order Filter</h4>
            </div>
            <div class="form-group  col-lg-6">
                <label>Tanggal Awal</label>
                <input type="text" name="early_date" class="form-control" id="datepicker">
            </div>
            <div class="form-group col-lg-6">
                <label>Tanggal Akhir</label>
                <input type="text" name="end_date" class="form-control" id="datepicker2">
            </div>
            <div class="form-group col-lg-12">
              <label>Supplier</label>
              <select class="select2 form-control" name="supplier">
                <option value="">-Pilih Supplier-</option>
                @foreach($suppliers as $supplier)
                  <option value="{{$supplier->id}}">{{$supplier->name}}</option>
                @endforeach
              </select>
            </div>
            <div class="form-group col-lg-12">
              <label>Status</label>
              <select class="select2 form-control" name="status">
                <option value="0">Not Approved</option>
                <option value="1">Approved</option>
              </select>
            </div>
            <div class="form-group col-lg-12">
              <input type="submit" class="btn btn-info" value="Submit"/>
              <a href="#" class="btn btn-default filter" data-toggle="control-sidebar">Batal</a>
            </div>
          </div>
       </form>
      </div>
    </div>
</aside> 
@push('scripts')
<script>
$(".content-wrapper").click(function(e) 
{
    var container = $("#sidebar-filter");
    if(!container.is(e.target) && container.has(e.target).length === 0 && !$(e.target).hasClass('filter'))
    {
        $(container).attr('class', 'control-sidebar control-sidebar-dark');
    }
});
</script>
@endpush

core/resources/views/reports/purchase/filter.blade.php
@extends('layouts.app')
@section('content')
<section class="content-header">
    <h1>
    Purchase
    <small>Report Purchase Order</small>
        <div class="pull-right">
            <a href="#" class="btn btn-success filter" data-toggle="control-sidebar">Filter</a>
        </div>
    </h1>
</section>
<div class="content">
    <div class="clearfix"></div>
    <div class="box box-danger">
        <div class="box-body">
            <table class="table table-responsive" id="sales-table">
                <thead>
                    <tr>
                        <th>Reference</th>
                        <th>Date</th>
                        <th>Supplier</th>
                        <th>Status</th>
                        <th>Amount</th>
                    </tr>
                </thead>
                <tbody>
                @foreach($hasil as $hasil)
                    <tr>
                        <td><a href="{{route('purchaseOrders.show', $hasil->id)}}">{{$hasil->reference}}</a></td>
                        <td>{{$hasil->suppliernya->name}}</td>
                        <td>{{date('Y-m-d', strtotime($hasil->date))}}</td>
                        <td>{{getStatusItem($hasil->status)}}</td>
                        <td>{{rupiah($hasil->amount)}}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@include('reports.purchase.addFilter')
@stop
@section('scripts')
<script type="text/javascript">
$(function() {
    $('#sales-table').DataTable();
});
</script>
@stop

core/resources/views/reports/purchase/index.blade.php
@extends('layouts.app')
@section('title', 'Report Purchase')
@section('content')
<section class="content-header">
 <h1>
    Purchase
    <small>Report Purchase Order </small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Purchase Order</li>
  </ol>
</section>
<div class="content">
	<section class="connectedSortable ui-sortable">
		<div class="box box-solid bg-red-gradient" style="position: relative;left: 0px;top: 0px;">
			<div class="box-header ui-sortable-handle" style="cursor: move;">
				<h3 class="box-title">Purchase Graph Per Quarter/Kwartal</h3>
				<div class="box-tools pull-right">
					<button type="button" class="btn bg-re btn-sm" data-widget="collapse"><i class="fa fa-minus"></i>
					</button>
				</div>
			</div>
			<div class="box-body border-radius-none">
				<div class="chart" id="line-chart" style="height: 250px;">
					
				</div>
			</div>
		</div>
	</section>
	<div class="row">
		<div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-aqua">
            <div class="inner">
              <h3>{{$total_sales}}</h3>

              <p>Orders</p>
            </div>
            <div class="icon">
              <i class="ion ion-ios-cart"></i>
            </div>
            <a href="{{route('salesOrders.index')}}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <div class="col-lg-3 col-xs-6" >
          <!-- small box -->
          <div class="small-box bg-green"  style="min-height: 128px;">
            <div class="inner">
              <h3>{{$item_sold}}</h3>

              <p>Items Bought</p>
            </div>
            <div class="icon">
              <i class="ion ion-bag"></i>
            </div>
            <!-- <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a> -->
          </div>
        </div>
        <div class="col-lg-3 col-xs-6">
	        <div class="small-box bg-yellow" style="min-height: 128px;">
	            <div class="inner">
	              <h3 style="font-size: 24px;">{{$cost_value}}</h3>
	              <p>Cost Value</p>
	            </div>
	            <div class="icon">
	              <i class="ion ion-cash"></i>
	            </div>
            <!-- <a href="#" class="small-box-footer" style="margin-top: auto;">More info <i class="fa fa-arrow-circle-right"></i></a> -->
          	</div>
        </div>
        <div class="col-lg-3 col-xs-6">
	        <div class="small-box bg-red" style="min-height: 128px;">
	            <div class="inner">
	              <h3>{{$percentage}}<sup style="font-size: 20px">%</sup></h3>
	              <p>Percentage Compare A Month Ago</p>
	            </div>
	            <div class="icon">
	              <i class="ion ion-stats-bars"></i>
	            </div>
            <!-- <a href="#" class="small-box-footer" style="margin-top: auto;">More info <i class="fa fa-arrow-circle-right"></i></a> -->
          	</div>
        </div>
	</div>
	<div class="box box-solid">
		<div class="box-header ui-sortable-handle" style="cursor: move;">
			<h3 class="box-title">Purchase</h3>
			<div class="box-tools pull-right">
				<a href="#" class="btn btn-success filter" data-toggle="control-sidebar">Filter</a>
			</div>
		</div>
		<div class="box-body border-radius-none">
			<table class="table table-responsive" id="salesOrders-table">
			    <thead>
			        <tr>
              <th>#</th>
			        <th>Date</th>
			        <th>Numbers of Orders</th>
			        <th>Number of Quantity</th>
			        <th>Approx. Harga</th>
			        </tr>
			    </thead>
			</table>
		</div>
	</div>
</div>
@include('reports.purchase.addFilter')
@stop
@section('scripts')
<script type="text/javascript">
$(function() {
    var table = $('#salesOrders-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{!! route('datatables.purchaseReport') !!}',
        columns: [
            {render : function(data, type, row, meta){
                return meta.row + meta.settings._iDisplayStart+1;
            }, searchable : false, orderable: false},
            { data: 'date', name: 'date', render: function (data) {
                var date = new Date(data);
                var month = date.getMonth() + 1;
                var full = (date.length > 1 ? date : "0" + date.getDate() +"-" + (month.length > 1 ? month : "0" + month)  + "-"  + date.getFullYear()) ;
                var url = "purchase/detail/"+full;
                return '<a href="'+url+'">'+full+'</a>';
            }},
            { data: 'perDate',name: 'perDate' },
            { data: 'qtyPerDate',name: 'qtyPerDate' },
            { data: 'approxVal',name: 'approxVal', render: function(data){
            	return convertToRupiah(data);
            }}
        ]
    });
});
var line = new Morris.Line({
    element          : 'line-chart',
    resize           : true,
    data             : [
     @foreach($report_graph as $report)
      { y: '{{$report->year}} Q{{$report->quarter}}', item1: {{$report->idcount}} },
     @endforeach
    ],
    xkey             : 'y',
    ykeys            : ['item1'],
    labels           : ['Total SO'],
    lineColors       : ['#303030'],
    lineWidth        : 2,
    hideHover        : 'auto',
    gridTextColor    : '#fff',
    gridStrokeWidth  : 0.4,
    pointSize        : 4,
    pointStrokeColors: ['#efefef'],
    gridLineColor    : '#efefef',
    gridTextFamily   : ['Source Sans Pro','Helvetica Neue','Helvetica,Arial,sans-serif'],
    gridTextSize     : 13
  });
</script>
@stop

core/resources/views/reports/purchase/table.blade.php
@extends('layouts.app')
@section('content')
<section class="content-header">
    <h1>
    Purchase
    <small>Report Purchase Order</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Purchase Order Detail</li>
    </ol>
</section>
<div class="content">
    <div class="clearfix"></div>
    <div class="box box-danger">
        <div class="box-body">
            <table class="table table-responsive" id="sales-table">
                <thead>
                    <tr>
                        <th>Reference</th>
                        <th>Supplier</th>
                        <th>Amount</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
@stop
@section('scripts')
<script type="text/javascript">
$(function() {
    $('#sales-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{!! route('datatables.purchaseReportDetail', $value) !!}',
        columns: [
            { data: 'action', name: 'action'},
            { data: 'suppliernya.name',name: 'suppliernya.name' },
            { data: 'amount',name: 'amount',render : function(data){
                return convertToRupiah(data);
            }}
        ]
    });
});
</script>
@stop