core/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();


Route::group(['middleware' => 'auth'], function (){
	Route::get('/', 'Frontend\HomeController@index')->name('home');
	Route::get('/customer/cart', 'Frontend\HomeController@index');
	Route::get('/search/query={name}', 'Frontend\HomeController@index');
	Route::get('/{id}', 'Frontend\HomeController@index');
	/**
	 * BACKEND
	 */
	Route::group([ 'prefix' => 'private'], function(){
		Route::get('home', 'HomeController@index')->name('dashboard');
		Route::post('itemsBy', 'ReturnItemController@apiItems')->name('api.itemsBy');
		Route::get('getSku/{id}', 'ItemController@getSku')->name('getSku');
		Route::get('returnItem/approve/{id}', 'ReturnItemController@approve')->name('returnItems.approve');
		Route::get('getAlamat/{cus_id}/{type}', 'SalesOrderController@getAlamat')->name('getAlamat');
		Route::get('downloadCSVex', function(){
			return response()->download(Storage::disk('local')->getDriver()->getAdapter()->getPathPrefix().'/public/[CONTOH MARAVILLOSA].csv');
		})->name('downloadCSVex')->middleware('permission:item');
		Route::resource('warehouseTransfers', 'WarehouseTransferController')->middleware('permission:warehouse-transfer');
		Route::resource('items', 'ItemController')->middleware('permission:item');
		Route::resource('items-variant', 'ItemVariantController')->middleware('permission:item');
		Route::resource('activityLogs', 'ActivityLogController')->middleware('permission:activity-logs');
		Route::resource('returnItems', 'ReturnItemController')->middleware('permission:return-item');
		
		Route::group(['prefix' => 'sales', 'middleware' => 'permission:sales'], function (){
			Route::get('print-invoice/{id}', 'SalesOrderController@printInvoice')->name('print-invoice')->middleware('permission:sales-order');
			Route::get('sales/approve/{id}/{jenis}', 'SalesOrderController@approve')->name('salesOrders.approve')->middleware('permission:sales-order');
			Route::resource('salesOrders', 'SalesOrderController')->middleware('permission:sales-order');
			Route::resource('invoices', 'InvoicesController')->middleware('permission:invoice');
			Route::get('purchase/{id}', 'PurchaseOrderController@approve')->name('purchaseOrders.approve')->middleware('permission:purchase-order');
			Route::resource('purchaseOrders', 'PurchaseOrderController')->middleware('permission:purchase-order');
			Route::resource('shipments', 'ShipmentController')->middleware('permission:shipment');
			Route::get('shipments/create/{id}', 'ShipmentController@create')->name('shipments.buat')->middleware('permission:shipment');
			Route::get('shipments/approve/{id}', 'ShipmentController@approve')->name('shipments.approve')->middleware('permission:shipment');
		});
		
		Route::group(['prefix' => 'report', 'namespace' => 'Report', 'middleware' => 'permission:reports'], function (){
			Route::get('purchase', 'PurchaseController@index')->name('report.purchase')->middleware('permission:report-purchase');
			Route::get('purchase/detail/{date}', 'PurchaseController@detail')->name('report.purchase.detail')->middleware('permission:report-purchase');
			Route::get('sales', 'SalesController@index')->name('report.sales')->middleware('permission:report-sales');
			Route::get('sales/detail/{date}', 'SalesController@detail')->name('report.sales.detail')->middleware('permission:report-sales');
			Route::get('warehouses', 'WarehousesController@index')->name('report.warehouses')->middleware('permission:report-stock');
			/**	FILTER */
			Route::post('purchase/filter', 'PurchaseController@filter')->name('filter.purchase')->middleware('permission:report-purchase');
			Route::post('sales/filter', 'SalesController@filter')->name('filter.sales')->middleware('permission:report-sales');
			Route::post('warehouses/filter', 'WarehousesController@filter')->name('filter.item')->middleware('permission:report-stock');
			Route::get('item/find', 'WarehousesController@apiNamaBarang')->name('api.findNamaBarang')->middleware('permission:report-stock');
			Route::post('item/find/variant', 'WarehousesController@apiNamaVariant')->name('api.findNamaVariant')->middleware('permission:report-stock');
		});
		
		Route::group(['prefix' => 'setting', 'middleware'=> ['permission:settings']], function (){
			Route::resource('users', 'UsersController')->middleware('permission:users');
			Route::resource('warehouses', 'WarehouseController')->middleware('permission:warehouses');
			Route::resource('brands', 'BrandController')->middleware('permission:brands');
			Route::resource('categories', 'CategoryController')->middleware('permission:categories');
			Route::resource('salesType', 'SalesTypeController')->middleware('permission:sales-type');
			Route::resource('suplliers', 'SupllierController')->middleware('permission:suppliers');
			Route::resource('customers', 'CustomerController')->middleware('permission:customers');
			Route::resource('paymentMethods', 'PaymentMethodController')->middleware('permission:payment-methods');
			Route::resource('taxes', 'TaxController')->middleware('permission:taxes');
			Route::resource('permissions', 'PermissionController')->middleware('permission:permissions');
			Route::resource('roles', 'RolesController')->middleware('permission:roles');
			Route::resource('departments', 'DepartmentController');
			Route::resource('satuans', 'SatuanController');
			Route::resource('itemVariants', 'ItemVariantController');
		});
		
		Route::group(['prefix' => 'datatables'], function(){
			Route::get('user', 'DatatablesController@getUsers')->name('datatables.users');
			Route::get('warehouses', 'DatatablesController@getWarehouses')->name('datatables.warehouses');
			Route::get('brands', 'DatatablesController@getBrands')->name('datatables.brands');
			Route::get('categories', 'DatatablesController@getCategories')->name('datatables.categories');
			Route::get('sales', 'DatatablesController@getSales')->name('datatables.sales');
			Route::get('suplliers', 'DatatablesController@getSuplliers')->name('datatables.suplliers');
			Route::get('customers', 'DatatablesController@getCustomers')->name('datatables.customers');
			Route::get('items', 'DatatablesController@getItems')->name('datatables.items');
			Route::get('itemsSales', 'DatatablesController@getItemsSales')->name('datatables.itemsSales');
			Route::get('itemsPurchase', 'DatatablesController@getItemsPurchase')->name('datatables.itemsPurchase');
			Route::get('salesOrders', 'DatatablesController@getSalesOrders')->name('datatables.salesOrders');
			Route::get('paymentMethods', 'DatatablesController@getPaymentMethods')->name('datatables.paymentMethods');
			Route::get('warehouseTransfer', 'DatatablesController@getWarehouseTransfer')->name('datatables.warehouseTransfer');
			Route::get('itemsWT', 'DatatablesController@getItemsWT')->name('datatables.itemsWT');
			Route::get('logs', 'DatatablesController@getActivityLog')->name('datatables.logs');
			Route::get('purchaseOrder', 'DatatablesController@getPurchaseOrders')->name('datatables.purchaseOrder');
			Route::get('items/{id}/{jenis}', 'DatatablesController@getItemVariant')->name('datatables.itemVariant');
			Route::get('itemsSO/{id}', 'DatatablesController@getItemShipment')->name('datatables.itemSO');
			Route::get('salesReport', 'DatatablesController@salesReport')->name('datatables.salesReport');
			Route::get('sales/detail/{date}', 'DatatablesController@salesReportDetail')->name('datatables.salesReportDetail');
			Route::get('purchaseReport', 'DatatablesController@purchaseReport')->name('datatables.purchaseReport');
			Route::get('purchase/detail/{date}', 'DatatablesController@purchaseReportDetail')->name('datatables.purchaseReportDetail');
			Route::get('warehouseReport', 'DatatablesController@warehouseReport')->name('datatables.warehouseReport');
			Route::get('returnItems', 'DatatablesController@returnItems')->name('datatables.returnItems');
			Route::get('itemsReturns/{id}', 'DatatablesController@itemsReturn')->name('datatables.itemsReturn');
			/**
			 * Datatable as Service
			 */
			Route::get('invoices/paid', 'InvoicesController@index')->name('datatables.invoicesUnpaid');
			Route::get('invoices/unpaid', 'InvoicesController@getPaid')->name('datatables.invoicesPaid');
			Route::get('salesOrders/approve', 'SalesOrderController@getApproved')->name('datatables.soApproved');
			Route::get('salesOrders/unapprove', 'SalesOrderController@index')->name('datatables.soUnapproved');
			Route::get('shipments/shipped', 'ShipmentController@getApproved')->name('datatables.shipmentApproved');
			Route::get('shipments/unshipped', 'ShipmentController@index')->name('datatables.shipmentUnapproved');
		});
	});
});

core/app/Models/ReturnItem.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Wildside\Userstamps\Userstamps;
use Spatie\Activitylog\Traits\LogsActivity;
use App\Traits\Uuids;

/**
 * Class ReturnItem
 * @package App\Models
 * @version March 11, 2018, 2:18 pm UTC
 *
 * @property \Illuminate\Database\Eloquent\Collection permissionRole
 * @property string sales_id
 * @property string shipment_id
 * @property string keterangan
 * @property string created_by
 * @property string updated_by
 * @property string deleted_by
 */
class ReturnItem extends Model
{
    use SoftDeletes, Userstamps, LogsActivity, Uuids;

    public $table = 'return_item';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';

    protected static $logFillable = true;
    
    const CREATED_BY = 'created_by';
    const UPDATED_BY = 'updated_by';
    const DELETED_BY = 'deleted_by';

    protected $dates = ['deleted_at'];
    protected $primaryKey = 'id';
    protected $keyType = 'string';
    public $incrementing = false;

    public $fillable = [
        'sales_id',
        'shipment_id',
        'keterangan',
        'created_by',
        'updated_by',
        'deleted_by'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'string',
        'sales_id' => 'string',
        'shipment_id' => 'string',
        'keterangan' => 'string',
        'created_by' => 'string',
        'updated_by' => 'string',
        'deleted_by' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    public function createdBy(){
        return $this->belongsTo('\App\Models\Users', 'created_by');
    }

    public function sales(){
        return $this->belongsTo('\App\Models\SalesOrder', 'sales_id');
    }

    public function shipment(){
        return $this->belongsTo('\App\Models\Shipment', 'shipment_id');
    }

    public function returnItems(){
        return $this->hasMany('\App\Models\ReturnItemDetail','return_item_id');
    }
}

core/resources/views/return_items/create.blade.php
@extends('layouts.app')
@section('title', 'Return Item')
@section('content')
    <section class="content-header">
        <h1>
            Return Item
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-danger">

            <div class="box-body">
                <div class="row">
                    <form action="{{route('api.itemsBy')}}" method="POST" id="sales-form">{{csrf_field()}}<input type="hidden" name="type" value="sales" id="type"><input type="hidden" name="id" id="id"></form>
                    {!! Form::open(['route' => 'returnItems.store']) !!}

                        @include('return_items.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

core/resources/views/return_items/edit.blade.php
@extends('layouts.app')
@section('title', 'Return Item')
@section('content')
    <section class="content-header">
        <h1>
            Return Item
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($returnItem, ['route' => ['returnItems.update', $returnItem->id], 'method' => 'patch']) !!}

                        @include('return_items.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

core/resources/views/return_items/index.blade.php
@extends('layouts.app')
@section('title', 'Return Items')
@section('content')
    <section class="content-header">
        <h1 class="pull-left">Return Items</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('returnItems.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-danger">
            <div class="box-body">
                    @include('return_items.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

core/resources/views/return_items/show_print_shipment.blade.php
@php
  $item_count = ceil(count($returnItem->returnItems) / 13);
  $temp_item  = 10;
  $curent     = 0;
  $item_data  = array_chunk($returnItem->returnItems->toArray(), 13);
@endphp
<!DOCTYPE html>
<html>
<head>
  <title>Retur {{strtoupper(substr($returnItem->id, 0, 5))}}</title>
</head>
<style>
html, body {
    /*margin: 0;*/
    font-size: 11px;
  line-height: 150%;
}

@page {
  size: 21.59cm 13.97cm;
}

.logo {
  width: 30%;
}

.borderless td, .borderless th {
    border: none !important;
}
.s {
   border: none !important;
   background:white !important;
}
.bordertable{
  border-left: 1px solid #000000;
  border-bottom: 1px solid #000000;
  border-top: 1px solid #000000;
  border-right: 1px solid #000000;
}

.borderth{
  border-bottom: 1px solid #000000;
  /*border-top: 1px solid #000000;
  bord*/er-right: 1px solid #000000;
}
.bordertd{
  border-right: 1px solid #000000;
}
.classtr{
  size: 21.59cm 13.97cm;
}
tr.spaceUnder > td
{
  padding-bottom: -0.5em;
}

.footer {
  position: absolute;
  right: 0;
  bottom: 0;
  left: 0;
  padding: 1rem;
  text-align: center;
}


.break {
  page-break-after: always
}

</style>
<body style="margin: -30px -30px -30px -30px; font-family: Tahoma,Arial, sans-serif;" >
  @for($i = 0; $i < count($item_data); $i++)
  <!-- For untuk masing2 page -->
    <div id="wrapper">  
      <table >
        <tr>
          <td style="width: 557px; font-size: 20px blod;" colspan="7">RETURN ITEMS</td>
          <td colspan="2">No Return Item :</td>
          <td align="left">#{{strtoupper(substr($returnItem->id, 0, 5))}}</td>
        </tr>
        <tr>
          <td valign="top" rowspan="4">Bill To</td>
          <td colspan="5" style="padding: 5px;" class="bordertable"  width="60">{{(isset($returnItem->shipment)) ? $returnItem->shipment->salesOrder->buyer->name : $returnItem2->sales->buyer->name}}</td>
          <td></td>
          <td colspan="2">Invoice Date </td>
          <td></td>
        </tr>
        <tr>
          <td valign="top" rowspan="3" colspan="5" style="border-left: 1px solid #000000;border-bottom: 1px solid #000000;border-right: 1px solid #000000;padding: 5px " width="60">
            {{(isset($returnItem->shipment)) ? $returnItem->shipment->salesOrder->detailAlamat->warehouse : $returnItem2->sales->detailAlamat->warehouse}} <br>Phone: {{(isset($returnItem->shipment)) ? $returnItem->shipment->salesOrder->buyer->phone : $returnItem2->sales->buyer->phone}} Email: {{(isset($returnItem->shipment)) ? $returnItem->shipment->salesOrder->buyer->email : $returnItem2->sales->buyer->email}}
          </td>
          <td></td>
          <td></td>
          <td colspan="2" align="center">{{ date('d M Y', strtotime($returnItem->created_at)) }}</td>
        </tr>
        <tr>
          <td></td>
          <td>Term</td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td>Salesman</td>
          <td colspan="2" class="bordertable" align="center"> {{$returnItem->createdBy->name}}</td>
        </tr>
      </table>
      <table id="salesInvoice">
        <tr>
          <td align="left" style="width: 200px" class="borderth">Item Description</td>
          <td align="left" style="width: 80px;" class="borderth">Qty</td>
          <td align="left" style="width: 100px;" class="borderth">Warehouse</td>
        </tr>
        @php
          (float)$tot = $dis = $rp = $discP = $discPt = 0;
        @endphp
        @foreach($item_data[$i] as $k => $items)
            @php
              $itemF = (object)$items;
              $item = (object)$itemF->items;
              $itemV = (object)$itemF->item_variant;
            @endphp
            <tr class="spaceUnder">
            <td>{{ $item->name }} ({{$itemV->warna}} {{(isset($itemV->pattern)) ? ',' : '' }} {{$itemV->pattern}}{{(isset($itemV->size)) ? ',' : '' }} {{$itemV->size}}{{(isset($itemV->roll)) ? ',' : '' }} {{$itemV->roll}}) {{(isset($itemF->partial)) ? '- '.$itemF->partial : '' }}</td>
            <td align="left">{{$itemF->qty}}</td>
            <td align="left">{{ $itemF->stock['name'] }}</td>
            </td>
          </tr>
        @endforeach
      </table>
      <br>
      <div class="footer">
        <table>
        <tr>
          <td  style="width: 379px; border-right: 1px solid black;border-top: 1px solid black;border-left: 1px solid black" colspan="7"></td>
          <td style="width: 100px;">&nbsp;</td>
          <td class="" style="width: 134px;"></td>
          <td class="" colspan="2" align="right" style="width: 100px"></td>
        </tr>
        <tr>
          <td colspan="7" style="border-bottom: 1px solid black; border-right: 1px solid black;border-left: 1px solid black"><p></p></td>
          <td style="width: 50px;"> </td>
          <td class="" style="width: 134px;"></td>
          <td class="" colspan="2" align="right" style="width: 100px"></td>
        </tr>
        <tr>
          <td colspan="2" align="center">Prepared By</td>
          <td></td>
          <td colspan="2" align="center">Approved By</td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td colspan="2" style="border-bottom: 1px solid #000000; height: 10px"></td>
          <td style="height: 25px"></td>
          <td colspan="2" style="border-bottom: 1px solid #000000"></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      </table>
      </div>
    </div>
    <div class="break"></div>
  @endfor

  
</body>
</html>

core/resources/views/return_items/table.blade.php
<table class="table table-responsive" id="returnItems-table">
    <thead>
        <tr>
            <th>Sales</th>
            <th>Shipment</th>
            <th>Keterangan</th>
            <th>Action</th>
        </tr>
    </thead>
</table>
@section('scripts')
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.1/css/buttons.dataTables.min.css">
<script src="https://cdn.datatables.net/buttons/1.5.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.html5.min.js"></script>
<script>
$(function() {
    $('#returnItems-table').DataTable({
        processing: true,
        serverSide: true,
        dom : 'Blfrtip',
        buttons : ['pdfHtml5', 'excelHtml5'],
        ajax: '{!! route('datatables.returnItems') !!}',
        columns: [
            { data: 'sales.reference', name: 'sales.reference' , render:function(data, row, metaData){
                if (data) {
                    return '<a href="{{url('private/sales/salesOrders')}}/'+metaData.sales_id+'">'+metaData.sales.reference+'</a>';
                }
                return '-';
            }},
            { data: 'shipment.reference', name: 'shipment.reference', render:function(data, row, metaData){
                if (data) {
                    return '<a href="{{url('private/sales/shipments')}}/'+metaData.shipment_id+'">'+metaData.shipment.reference+'</a>';
                }
                return '-';
            }},
            { data: 'keterangan',name: 'keterangan', render:function(data){
                if(data){
                    return data;
                }
                return '-';
            }},
            { data : 'action' ,name:'action'}
        ]
    });
});
</script>
@stop